#!/bin/bash
set -e
# 用于构建RPM包

YUM_TOP_DIR="/usr/src/packages"

clear_dir () {
  rm -r "${YUM_TOP_DIR}/BUILD/"*
  rm -r "${YUM_TOP_DIR}/BUILDROOT/"*
  rm -r "${YUM_TOP_DIR}/SOURCES/"*
}

# 读取update.json，获取顶级键的Name即可
file="update.json"
# 遍历顶级键name
for name in $(jq -r 'keys[]' "$file"); do

  # 由Name去复制SOURCE
  cp "packages/${name}/"* "${YUM_TOP_DIR}/SOURCES"
  SPEC_FILE="${YUM_TOP_DIR}/SOURCES/${name}.spec"
  # 安装依赖
  echo "为 $name 安装依赖"
  zypper --non-interactive install \
    "$(rpmspec --parse ${SPEC_FILE} | grep BuildRequires | tr -s ' ' | cut -d' ' -f2)"

  # 构建包
  echo "开始构建 $name"
  rpmbuild --undefine=_disable_source_fetch -bb "$SPEC_FILE"
  clear_dir
done
