#!/usr/bin/env bash
set -euo pipefail

# gen diff.json based on spec and status
# Usage: $0 spec.json status.json

spec_file="$1"
status_file="$2"

# spec.json sould not be empty
if [ "$(jq 'length' "$spec_file")" -eq 0 ]; then
  echo "Error: spec.json is empty" >&2
  exit 1
fi

jq --slurpfile status "$status_file" '
  # all packages in spec
  to_entries
  | map(
      .key as $name
      | .value[] | . + {name: $name}
    ) as $spec_pkgs
  # all packages in status
  | ($status[0] | to_entries
      | map(
          .key as $name
          | .value[] | . + {name: $name}
        )
    ) as $status_pkgs
  # find packages in spec but not in status
  | ($spec_pkgs - $status_pkgs)
  # arrange packages in format { name: [ {...}, {...} ] }
  | group_by(.name)
  | map({ (.[0].name): map(del(.name)) })
  | add
  # output {} when no difference
  // {}
' "$spec_file"
