#!/bin/bash
set -e
# 为rpm或repomd.xml签名

YUM_TOP_DIR="/usr/src/packages"
LOCAL_COPY="copy"

import_secret() {
  if [[ -n "$GPG_SEC_ID" ]]; then
    echo "导入GPG Key"
    echo "%_gpg_name ${GPG_SEC_ID}" > ~/.rpmmacros
    echo "$GPG_SEC" | gpg --import --batch --yes
  else
    echo "GPG KEY不存在"
  fi
}


if [[ "$1" == "rpm" ]]; then
  echo "为RPM签名"
  find "${YUM_TOP_DIR}/RPMS" -type f -name "*.rpm" -exec rpm --addsign {} \;
elif [[ "$1" == "metadata" ]]; then
  echo "为repomd.xml签名"
  gpg --detach-sign --armor --batch --yes "${LOCAL_COPY}/repodata/repomd.xml"
elif [[ "$1" == "setup" ]]; then
  import_secret
else
  echo 错误的参数："$@"
  exit 1
fi
