name: Auto build RPMs
on:
  workflow_call:
    inputs:
      pkg-path:
        description: "A relative path where can found spec files"
        required: true
        type: string
      rclone-repo-name:
        description: "Section name of the yum repository in Rclone"
        required: false
        type: string
        default: remote
      metadata-workflow-name:
        required: true
        type: string
      matrix-file:
        required: true
        type: string
      hostname:
        required: true
        type: string
      build-srpm:
        required: false
        type: boolean
        default: false
      hooks-dir:
        required: true
        type: string

    secrets:
      RCLONE_CONFIG_SECTION:
        description: "Extract from the rclone.conf file content, only the repository section is needed"
        required: true
      GPG_SECRET:
        required: true
      GPG_SECRET_ID:
        required: true
      TOKEN:
        required: false

jobs:
  prepare:
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash
    outputs:
      matrix: ${{ steps.gen-matrix.outputs.matrix }}
    steps:
      - name: Checkout tools repository
        uses: actions/checkout@v5
        with:
          repository: anm1n/yum2
          path: tools
          fetch-depth: 1
          token: ${{ secrets.TOKEN || secrets.GITHUB_TOKEN }}

      - name: Checkout SPECs repository
        uses: actions/checkout@v5
        with:
          path: specs
          fetch-depth: 1

      - name: Cache prebuild Rclone deb
        uses: actions/cache@v4
        with:
          path: rclone.deb
          key: rclone-deb-1.71.0

      - name: Setup Rclone
        run: |
          if [ ! -f rclone.deb ]; then
            curl -o rclone.deb https://downloads.rclone.org/v1.71.0/rclone-v1.71.0-linux-amd64.deb
          fi

          echo '53e35eac5cb5e6e4a9cc04ffe28d5ace695fd335a156f8d17b11df37739b725f  rclone.deb' | sha256sum -c
          sudo dpkg -i rclone.deb
          mkdir -vp ~/.config/rclone

      - name: Pull status.json
        env:
          RCLONE_CONFIG_SECTION: ${{ secrets.RCLONE_CONFIG_SECTION }}
          RCLONE_REPO_NAME: ${{ inputs.rclone-repo-name }}
        run: |
          echo "$RCLONE_CONFIG_SECTION" | base64 -d > ~/.config/rclone/rclone.conf

          if rclone ls ${RCLONE_REPO_NAME}:/repodata/status.json > /dev/null ; then
            rclone copy ${RCLONE_REPO_NAME}:/repodata/status.json .
          else
            echo "Warn: status.json not exist on $RCLONE_REPO_NAME"
            echo "Warn: will rebuild everything"
            echo '{}' > status.json
          fi

          shred -u ~/.config/rclone/rclone.conf

      - name: Gen spec.json
        run: |
          tools/scripts/gen-spec -o spec.json -r specs/${{ inputs.pkg-path }} -m specs/${{ inputs.matrix-file }}
          cat spec.json

      - name: Gen diff.json
        run: |
          tools/scripts/gen-diff spec.json status.json > diff.json
          cat diff.json

      - name: Gen matrix
        id: gen-matrix
        run: |
          tools/scripts/gen-matrix -d diff.json -r specs/${{ inputs.pkg-path }} -m specs/${{ inputs.matrix-file }} > matrix.json
          cat matrix.json

          echo "matrix<<__EOF___" >> $GITHUB_OUTPUT
          cat matrix.json >> $GITHUB_OUTPUT
          echo "__EOF___" >> $GITHUB_OUTPUT


  build:
    needs: prepare
    if: ${{ join(fromJson(needs.prepare.outputs.matrix)) != '' }}
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash
    container:
      image: ${{ matrix.image }}
      options: --hostname ${{ inputs.hostname }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.prepare.outputs.matrix) }}

    steps:
      - name: Checkout tools repository
        uses: actions/checkout@v5
        with:
          repository: anm1n/yum2
          path: tools
          fetch-depth: 1
          token: ${{ secrets.TOKEN || secrets.GITHUB_TOKEN }}

      - name: Checkout SPECs repository
        uses: actions/checkout@v5
        with:
          path: specs
          fetch-depth: 1

      - name: Print matrix info
        run: |
          echo "================= Build Matrix Info ================="
          printf "%-10s | %s\n" "PKG"     "${{ matrix.pkg }}"
          printf "%-10s | %s\n" "VERSION" "${{ matrix.version }}"
          printf "%-10s | %s\n" "RELEASE" "${{ matrix.release }}"
          printf "%-10s | %s\n" "DISTRO"  "${{ matrix.distro }}"
          printf "%-10s | %s\n" "BRANCH"  "${{ matrix.branch }}"
          printf "%-10s | %s\n" "IMAGE"   "${{ matrix.image }}"
          echo "====================================================="

      - name: Setup basic environment
        run: |
          if command -v dnf > /dev/null; then
            dnf install -y findutils
          else
            zypper --non-interactive ref
            # for whatever reason
            # dnf not work when using libcurl-mini4 instead of libcurl4
            zypper --non-interactive install findutils libcurl4
          fi

      - name: Cache prebuild yq
        uses: actions/cache@v4
        with:
          path: yq
          key: yq-amd64-4.47.1

      - name: Setup yq
        run: |
          if [ ! -f yq ]; then
            curl -Lo yq https://github.com/mikefarah/yq/releases/download/v4.47.1/yq_linux_amd64
          fi
          echo '0fb28c6680193c41b364193d0c0fc4a03177aecde51cfc04d506b1517158c2fb  yq' | sha256sum -c
          install -m 755 yq /usr/bin/yq

      - name: Run pre hooks
        run: |
          tools/scripts/hook -p specs/${{ inputs.pkg-path }}/${{ matrix.pkg }} -g specs/${{ inputs.hooks-dir }} -d ${{ matrix.distro }} -b ${{ matrix.branch }} -t prebuild -e

      - name: Download sources
        run: |
          mkdir -p specs/${{ inputs.pkg-path }}/${{ matrix.pkg }}/source
          tools/scripts/download -p specs/${{ inputs.pkg-path }}/${{ matrix.pkg }}

      - name: Setup build tree
        id: setup-tree
        run: |
          echo '%_topdir  %(echo $HOME)/rpmbuild' >> ~/.rpmmacros
          echo '%debug_package %{nil}' >> ~/.rpmmacros
          echo '%source_date_epoch_from_changelog %{nil}' >> ~/.rpmmacros
          rpmdev-setuptree
          echo "topdir=$HOME/rpmbuild" >> $GITHUB_OUTPUT

      - name: Build RPM
        env:
          BUILD_SRPM: ${{ inputs.build-srpm }}
        run: |
          mkdir -vp ~/BUILD_RPMS/x86_64
          mkdir -vp ~/BUILD_RPMS/noarch
          cp -v specs/${{ inputs.pkg-path }}/${{ matrix.pkg }}/${{ matrix.pkg }}.spec ${{ steps.setup-tree.outputs.topdir }}/SPECS
          cp -v specs/${{ inputs.pkg-path }}/${{ matrix.pkg }}/source/* ${{ steps.setup-tree.outputs.topdir }}/SOURCES

          # Build RPMs
          # also copy SRPMs if build
          if [ "$BUILD_SRPM" == true ]; then
            rpmbuild -ba ${{ steps.setup-tree.outputs.topdir }}/SPECS/${{ matrix.pkg }}.spec

            mkdir -vp ~/BUILD_SRPMS
            find ${{ steps.setup-tree.outputs.topdir }}/SRPMS -type f -name "*.rpm" ! -name "*debugsource*" ! -name "*debuginfo*" -exec cp -v {} ~/BUILD_SRPMS \;
          else
            rpmbuild -bb ${{ steps.setup-tree.outputs.topdir }}/SPECS/${{ matrix.pkg }}.spec
          fi

          # copy RPMs for later operations
          if [ -d ${{ steps.setup-tree.outputs.topdir }}/RPMS/x86_64 ]; then
            find ${{ steps.setup-tree.outputs.topdir }}/RPMS/x86_64 -type f -name "*.rpm" ! -name "*debugsource*" ! -name "*debuginfo*" -exec cp -v {} ~/BUILD_RPMS/x86_64 \;
          fi

          if [ -d ${{ steps.setup-tree.outputs.topdir }}/RPMS/noarch ]; then
            find ${{ steps.setup-tree.outputs.topdir }}/RPMS/noarch -type f -name "*.rpm" ! -name "*debugsource*" ! -name "*debuginfo*" -exec cp -v {} ~/BUILD_RPMS/noarch \;
          fi

      - name: Run post hooks
        run: |
          tools/scripts/hook -p specs/${{ inputs.pkg-path }}/${{ matrix.pkg }} -g specs/${{ inputs.hooks-dir }} -d ${{ matrix.distro }} -b ${{ matrix.branch }} -t postbuild -e

      - name: Setup GPG
        env:
          GPG_SECRET: ${{ secrets.GPG_SECRET }}
        run: |
          if dnf list available gpg2; then
            dnf install gpg2
          elif dnf list available gnupg2; then
            dnf install gnupg2
          elif dnf list available gnupg; then
            dnf install gnupg
          elif dnf list available gpg; then
            dnf install gpg
          else
            echo "Error: can't install GPG"
            exit 1
          fi

          echo "Importing GPG key"
          echo "$GPG_SECRET" | base64 -d | gpg --import --batch --yes

      - name: Sign RPM
        env:
          GPG_SECRET_ID: ${{ secrets.GPG_SECRET_ID }}
          BUILD_SRPM: ${{ inputs.build-srpm }}
        run: |
          find "$HOME/BUILD_RPMS/x86_64" -name "*.rpm" -type f -exec rpmsign --addsign {} --define "_gpg_name $GPG_SECRET_ID" \;
          find "$HOME/BUILD_RPMS/noarch" -name "*.rpm" -type f -exec rpmsign --addsign {} --define "_gpg_name $GPG_SECRET_ID" \;

          if [ "$BUILD_SRPM" == true ]; then
            rpmsign --addsign ~/BUILD_SRPMS/*.rpm --define "_gpg_name $GPG_SECRET_ID"
          fi

          gpg --batch --yes --delete-secret-keys "$GPG_SECRET_ID"

      - name: Cache prebuild Rclone rpm
        uses: actions/cache@v4
        with:
          path: rclone.rpm
          key: rclone-rpm-1.71.0

      - name: Setup Rclone
        run: |
          if [ ! -f rclone.rpm ]; then
            curl -o rclone.rpm https://downloads.rclone.org/v1.71.0/rclone-v1.71.0-linux-amd64.rpm
          fi

          echo '7dcae58067ee30da79fe0be06fcdc0c7b163aa23d13fd3c54043a3288ade75cc  rclone.rpm' | sha256sum -c
          rpm -i rclone.rpm
          mkdir -vp ~/.config/rclone

      - name: Upload to repo
        env:
          RCLONE_CONFIG_SECTION: ${{ secrets.RCLONE_CONFIG_SECTION }}
          RCLONE_REPO_NAME: ${{ inputs.rclone-repo-name }}
        run: |
          echo "$RCLONE_CONFIG_SECTION" | base64 -d > ~/.config/rclone/rclone.conf

          # rclone copy takes the 2nd argument as the target directory
          # It recursively creates it if it doesn't exist
          # So, we just copy it
          rclone copy ~/BUILD_RPMS/x86_64 ${RCLONE_REPO_NAME}:/${{ matrix.distro }}/${{ matrix.branch }}/x86_64 --progress
          rclone copy ~/BUILD_RPMS/noarch ${RCLONE_REPO_NAME}:/${{ matrix.distro }}/${{ matrix.branch }}/noarch --progress

          if [ "$BUILD_SRPM" == true ]; then
            rclone copy ~/BUILD_SRPMS ${RCLONE_REPO_NAME}:/${{ matrix.distro }}/${{ matrix.branch }}/source --progress
          fi

          shred -u ~/.config/rclone/rclone.conf

      - name: Clean environment
        if: always()
        env:
          GPG_SECRET_ID: ${{ secrets.GPG_SECRET_ID }}
        run: |
          test -e ~/.config/rclone/rclone.conf && shred -u ~/.config/rclone/rclone.conf
          gpg --batch --yes --delete-secret-keys "$GPG_SECRET_ID" || true
