name: Update metadata of yum repo
on:
  workflow_call:
    inputs:
      rclone-repo-name:
        description: "Section name of the yum repository in Rclone"
        required: false
        type: string
        default: remote

    secrets:
      RCLONE_CONFIG_SECTION:
        description: "Extract from the rclone.conf file content, only the repository section is needed"
        required: true
      GPG_SECRET:
        description: ""
        required: true
      GPG_SECRET_ID:
        required: true
      TOKEN:
        required: false

jobs:
  job1:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          repository: anm1n/yum2
          path: tools
          fetch-depth: 1
          token: ${{ secrets.TOKEN || secrets.GITHUB_TOKEN }}

      - name: Install Rclone, GPG, createrepo
        run: |
          sudo apt update
          sudo apt install -y rclone gpg createrepo-c dnf

      - name: Pull yum repo
        env:
          RCLONE_CONFIG_VAL: ${{ secrets.RCLONE_CONFIG_SECTION }}
          RCLONE_REPO_NAME: ${{ inputs.rclone-repo-name }}
        run: |
          mkdir -p ~/.config/rclone
          echo "$RCLONE_CONFIG_VAL" > ~/.config/rclone/rclone.conf
          mkdir copy
          rclone copy ${RCLONE_REPO_NAME}:/ copy/ --progress
          shred -u ~/.config/rclone/rclone.conf

      - name: Update yum repo metadata
        run: |
          test -e copy/repodata/repomd.xml && rm -v copy/repodata/*
          createrepo_c copy/

      - name: Sign repomd.xml
        env:
          GPG_SEC: ${{ secrets.GPG_SECRET }}
          GPG_SEC_ID: ${{ secrets.GPG_SECRET_ID }}
        run: |
          echo "import GPG key"
          echo "$GPG_SEC" | gpg --import --batch --yes
          gpg --detach-sign --armor --batch --yes --local-user "$GPG_SEC_ID" "copy/repodata/repomd.xml"
          gpg --batch --yes --delete-secret-keys "$GPG_SEC_ID"

      - name: Generate status.json
        run: tools/scripts/gen-status -r "$(pwd)/copy" -o copy/repodata/status.json

      - name: Push metadata
        env:
          RCLONE_CONFIG_VAL: ${{ secrets.RCLONE_CONFIG_SECTION }}
          RCLONE_REPO_NAME: ${{ inputs.rclone-repo-name }}
        run: |
          echo "$RCLONE_CONFIG_VAL" > ~/.config/rclone/rclone.conf
          rclone sync copy/ ${RCLONE_REPO_NAME}:/ --progress
          shred -u ~/.config/rclone/rclone.conf

      - name: Clean secrets
        if: always()
        env:
          GPG_SEC_ID: ${{ secrets.GPG_SECRET_ID }}
        run: |
          test -e ~/.config/rclone/rclone.conf && shred -u ~/.config/rclone/rclone.conf
          gpg --batch --yes --delete-secret-keys "$GPG_SEC_ID" || true
