name: Update metadata of yum repo
on:
  workflow_call:
    inputs:
      rclone-repo-name:
        description: "Section name of the yum repository in Rclone"
        required: false
        type: string
        default: remote

    secrets:
      RCLONE_CONFIG_SECTION:
        description: "Extract from the rclone.conf file content, only the repository section is needed"
        required: true
      GPG_SECRET:
        description: ""
        required: true
      GPG_SECRET_ID:
        required: true
      TOKEN:
        required: false

jobs:
  job1:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          repository: anm1n/yum2
          path: tools
          fetch-depth: 1
          token: ${{ secrets.TOKEN || secrets.GITHUB_TOKEN }}

      - name: Install GPG, createrepo
        run: |
          sudo apt update
          sudo apt install -y gpg createrepo-c dnf

      - name: Cache prebuild Rclone deb
        uses: actions/cache@v4
        with:
          path: rclone.deb
          key: rclone-deb-1.71.0

      - name: Install Rclone
        run: |
          if [ ! -f rclone.deb ]; then
            curl -o rclone.deb https://downloads.rclone.org/v1.71.0/rclone-v1.71.0-linux-amd64.deb
          fi

          echo '53e35eac5cb5e6e4a9cc04ffe28d5ace695fd335a156f8d17b11df37739b725f  rclone.deb' | sha256sum -c
          sudo dpkg -i rclone.deb
          mkdir -vp ~/.config/rclone

      - name: Pull yum repo
        env:
          RCLONE_CONFIG_VAL: ${{ secrets.RCLONE_CONFIG_SECTION }}
          RCLONE_REPO_NAME: ${{ inputs.rclone-repo-name }}
        run: |
          echo "$RCLONE_CONFIG_VAL" | base64 -d > ~/.config/rclone/rclone.conf
          mkdir -v copy
          rclone copy ${RCLONE_REPO_NAME}:/ copy/ --progress
          shred -u ~/.config/rclone/rclone.conf

      - name: Import GPG key
        env:
          GPG_SEC: ${{ secrets.GPG_SECRET }}
        run: |
          echo "$GPG_SEC" | base64 -d | gpg --import --batch --yes

      - name: Generate yum repodata, also sign repomd.xml
        env:
          GPG_SEC_ID: ${{ secrets.GPG_SECRET_ID }}
        run: |
          tools/scripts/gen-repodata -r copy -s "$GPG_SEC_ID"
          gpg --batch --yes --delete-secret-keys "$GPG_SEC_ID"

      - name: Generate status.json
        run: |
          tools/scripts/gen-status -r "$(pwd)/copy" -o copy/status.json
          cat copy/status.json

      - name: Push metadata
        env:
          RCLONE_CONFIG_VAL: ${{ secrets.RCLONE_CONFIG_SECTION }}
          RCLONE_REPO_NAME: ${{ inputs.rclone-repo-name }}
        run: |
          echo "$RCLONE_CONFIG_VAL" | base64 -d > ~/.config/rclone/rclone.conf
          rclone sync copy/ ${RCLONE_REPO_NAME}:/ --progress
          shred -u ~/.config/rclone/rclone.conf

      - name: Clean environment
        if: always()
        env:
          GPG_SEC_ID: ${{ secrets.GPG_SECRET_ID }}
        run: |
          test -e ~/.config/rclone/rclone.conf && shred -u ~/.config/rclone/rclone.conf
          gpg --batch --yes --delete-secret-keys "$GPG_SEC_ID" || true
